# Start Up DMX Persistent Dependencies
# Services: RabbitMQ3.7, RavenDB4, MS SQL Server 17

version: '3'
services:
  rmq:
    image: rabbitmq:3.7-management-alpine
    container_name: rabbitmq_37_m_a
    hostname: rabbitmq1
    restart: unless-stopped
    ports:
      - ${RABBITMQ_HTTP}:15672           #http
      - ${RABBITMQ_AMQP}:5672            #amqp
      # - ${RABBITMQ_CLUSTERING}:25672   #clustering
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
  mssql:
    container_name: mssql-server-17
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    depends_on: 
      - rmq
      - rvn4
    ports:
      - ${MSSQL_PORT}:1433
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${MSSQL_ACCEPT_EULA}
      MSSQL_PID: ${MSSQL_PID}
    volumes:
      - ${MSSQL_DIR_DATA}:/var/opt/mssql/data
      - ${MSSQL_DIR_BAK}:/var/opt/mssql/backup
  rvn4:
    container_name: ravendb_latest
    image: ravendb/ravendb:latest
    restart: unless-stopped
    depends_on: 
      - rmq
    ports:
      - ${RAVENDB4_BIND_TCP_PORT}:38888
      - ${RAVENDB4_BIND_PORT}:8080
    environment:
      RAVEN_ARGS: ${RAVENDB4_ARGS}
      RAVEN_Security_UnsecuredAccessAllowed: ${RAVENDB4_SECURITY_UNSECURED_ACCESS_ALLOW}
    volumes:
      - ${RAVENDB4_DIR_CONFIG}:/opt/RavenDB/config
      - ${RAVENDB4_DIR_DATA}:/opt/RavenDB/Server/RavenData   
  claims:
      container_name: bl-claims
      image: bl-claims
      restart: unless-stopped
      depends_on: 
        - rmq
        - rvn4
  notify:
      container_name: bl-notify
      image: bl-notify
      restart: unless-stopped
      depends_on: 
        - rmq
        - rvn4
  orig-core:
      container_name: orig-core
      image: orig-core
      restart: unless-stopped
      depends_on: 
        - claims
        - notify
