# https://neo4j.com/docs/operations-manual/current/installation/docker/
# docker-compose -f docker-compose.yml up --force-recreate --build -d
# docker-compose -f docker-compose.yml down
# used tags: 4.2-enterprise
# GraphiQL plugin - https://github.com/neo4j-graphql/neo4j-graphql

version: "3"

services:
  n4j-server:
    container_name: n4j-42-e
    image: neo4j:4.2-enterprise
    volumes:
      - ${NEO4J_path}\data:/var/lib/neo4j/data
      - ${NEO4J_path}\logs:/logs
      - ${NEO4J_path}\conf:/var/lib/neo4j/conf
      - ${NEO4J_path}\plugins:/plugins
      - ${NEO4J_path}\import:/var/lib/neo4j/import
      - ${NEO4J_path}\certificates:/var/lib/neo4j/certificates
      - ${NEO4J_path}\run:/var/lib/neo4j/run
    ports:
      - ${NEO4J_HTTP}:7474   # Http protocol - Used by the Neo4j Browser. Also used by REST API. (Development)
      - ${NEO4J_BOLT}:7687   # Bolt protocol - Used by Cypher Shell and by the Neo4j Browser.
      - ${NEO4J_HTTPS}:7473  # Https protocol - Used by the Neo4j Browser. Also used by REST API. (Production)
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
      NEO4J_ACCEPT_LICENSE_AGREEMENT: ${NEO4J_ACCEPT_LICENSE_AGREEMENT}
      NEO4J_dbms_security_procedures_unrestricted: ${NEO4J_dbms_security_procedures_unrestricted}
      NEO4J_dbms_security_procedures_whitelist: ${NEO4J_dbms_security_procedures_whitelist}
      NEO4J_dbms_allow_upgrade: ${NEO4J_dbms_allow_upgrade}
      NEO4J_dbms_backup_enabled: ${NEO4J_dbms_backup_enabled}
      NEO4J_apoc_export_file_enabled: ${NEO4J_apoc_export_file_enabled}
      NEO4J_apoc_import_file_enabled: ${NEO4J_apoc_import_file_enabled}
      NEO4J_apoc_import_file_use__neo4j__config: ${NEO4J_apoc_import_file_use__neo4j__config}
      NEO4JLABS_PLUGINS: ${NEO4JLABS_PLUGINS}
      NEO4J_dbms_memory_pagecache_size: ${NEO4J_dbms_memory_pagecache_size}
    restart: unless-stopped
