# https://neo4j.com/docs/operations-manual/current/installation/docker/
# docker-compose -f neo4j-docker-compose.yml up --force-recreate --build -d
# docker-compose -f neo4j-docker-compose.yml down
# used tags: 4.0-enterprise, 4.0.4-enterprise
# GraphiQL plugin - https://github.com/neo4j-graphql/neo4j-graphql

version: "3"

services:
  n4j-server:
    container_name: n4j-4-e
    image: neo4j:4.0.4-enterprise
    volumes:
      - c:\dkr\neo4j\data:/var/lib/neo4j/data
      - c:\dkr\neo4j\logs:/logs
      - c:\dkr\neo4j\conf:/var/lib/neo4j/conf
      - c:\dkr\neo4j\plugins:/plugins
      - c:\dkr\neo4j\import:/var/lib/neo4j/import
      - c:\dkr\neo4j\certificates:/var/lib/neo4j/certificates
      - c:\dkr\neo4j\run:/var/lib/neo4j/run
    ports:
      - ${NEO4J_HTTP}:7474 # 7474:7474   # Http protocol - Used by the Neo4j Browser. Also used by REST API. (Development)
      - ${NEO4J_BOLT}:7687 # 7687:7687   # Bolt protocol - Used by Cypher Shell and by the Neo4j Browser.
      # - ${NEO4J_HTTPS}:7473   # Https protocol - Used by the Neo4j Browser. Also used by REST API. (Production)
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
      NEO4J_ACCEPT_LICENSE_AGREEMENT: ${NEO4J_ACCEPT_LICENSE_AGREEMENT}
      NEO4J_apoc_export_file_enabled: ${NEO4J_apoc_export_file_enabled}
      NEO4J_apoc_import_file_enabled: ${NEO4J_apoc_import_file_enabled}
      NEO4J_apoc_import_file_use__neo4j__config: ${NEO4J_apoc_import_file_use__neo4j__config}
      NEO4J_fabric_database_name: ${NEO4J_fabric_database_name}
      NEO4J_fabric_graph_0_database: ${NEO4J_fabric_graph_0_database}
      NEO4J_fabric_graph_0_name: ${NEO4J_fabric_graph_0_name}
      NEO4J_fabric_graph_0_uri: ${NEO4J_fabric_graph_0_uri}
      NEO4J_fabric_graph_1_database: ${NEO4J_fabric_graph_1_database}
      NEO4J_fabric_graph_1_name: ${NEO4J_fabric_graph_1_name}
      NEO4J_fabric_graph_1_uri: ${NEO4J_fabric_graph_1_uri}
    restart: unless-stopped
