# https://github.com/pardahlman/docker-rabbitmq-cluster/blob/master/docker-compose.yml
# docker-compose -f rabbitmq-docker-compose.yml up --force-recreate --build -d
# docker-compose -f rabbitmq-docker-compose.yml down
# tags used: rabbitmq:3.7-management-alpine, rabbitmq:3.7-management
version: "3"

services:
  rabbitmq1:
    image: rabbitmq:3.7-management-alpine
    container_name: rabbitmq_37_m_a
    hostname: rabbitmq1
    restart: unless-stopped
    # command: sh -c "rabbitmq-plugins enable rabbitmq_management"
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    ports:
      - ${HTTP}:15672 #http
      - ${AMQP}:5672 #amqp
      # - ${CLUSTERING}:25672   #clustering
    # volumes:
      # - c:\dkr\rmq\:/etc/rabbitmq/
