# docker run -p 9200:9200 -p 9300:9300 --restart unless-stopped -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.5.4
# docker-compose -f elastic-search-docker-compose.yml up --force-recreate --build -d
# docker-compose -f elastic-search-docker-compose.yml down

version: '3.9'

volumes:
  data00:
    driver: local
  kibana00:
    driver: local

networks:
  elastic:
    driver: bridge

services:
  elasticsearch:
    container_name: elastic_search
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    restart: unless-stopped
    env_file:
      - env.txt
    ports:
      - 9200:9200   
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data00:/usr/share/elasticsearch/data
    networks:
      - elastic
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.4.3
    ports:
      - 5601:5601
    volumes:
      - kibana00:/usr/share/kibana/config
    networks:
      - elastic