# https://stackoverflow.com/questions/44002643/how-to-use-the-official-docker-elasticsearch-container
# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
# docker-compose -f elk-docker-compose.yml up --force-recreate --build -d
# docker-compose -f elk-docker-compose.yml down
version: '2.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch_654
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
    networks:
      - esnet
  
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.0
    container_name: kibana_620
    environment:
      - SERVER_HOST=0.0.0.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  headPlugin:
    image: mobz/elasticsearch-head:5-alpine
    container_name: head_540
    ports:
      - 9100:9100

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet: