version: '3.6'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  
  graphql-engine:
    image: hasura/graphql-engine:v2.0.9
    ports:
    - "1001:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  
  pgadmin:
    image: dpage/pgadmin4:latest
    ports: 
      - 81:80
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@thumbezatech.co.za
      - PGADMIN_DEFAULT_PASSWORD=postgrespassword
    depends_on: 
      - postgres
    restart: unless-stopped

volumes:
  db_data:
