# docker-compose -f sql-docker-compose.yml up --force-recreate --build -d
# docker-compose -f sql-docker-compose.yml down
# used tags: mcr.microsoft.com/mssql/server:2017-latest-ubuntu

# to connect to instance: 127.0.0.1,${PORT}; userId=sa; password=${SA_PASSWORD}

# copy files into container:
# $> docker cp e:\dkr\mssql\backup\backupfile.bak mssql-server-17:/var/opt/mssql/data/backupfile.bak
# copy files out of container:
# $> docker cp mssql-server-17:/var/opt/mssql/data/backupfile.bak e:\dkr\mssql\backup\backupfile.bak

version: "3"

services:
  mssql-server:
    container_name: mssql-server-19
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - ${PORT}:1433
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_PID: ${MSSQL_PID}
      MSSQL_MEMORY_LIMIT_MB: ${MSSQL_MEMORY_LIMIT_MB}
      # MSSQL_AGENT_ENABLED: ${MSSQL_AGENT_ENABLED}
    restart: unless-stopped
    volumes:
      - ${DIR_DATA}:/var/opt/mssql/data
      - ${DIR_BAK}:/var/opt/mssql/backup
